# -*- coding: utf-8 -*-
"""Fuel Consumption Analysis System UI .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RK4VUsOwZwTZF-l4Zi8s0e1oteFKISRb

##### Fuel Consumption Analysis System UI #####
"""

import gradio as gr
import pandas as pd
import matplotlib.pyplot as plt
from datasets import load_dataset

dataset = load_dataset("scikit-learn/auto-mpg", split="train")
df = dataset.to_pandas()

def dataset_analysis():
    mean_val = df["mpg"].mean()
    var_val = df["mpg"].var()

    plt.plot(df["mpg"].head(50))
    plt.title("Fuel Efficiency Trend")
    plt.savefig("trend.png")
    plt.close()

    plt.hist(df["mpg"], bins=15)
    plt.title("Fuel Efficiency Distribution")
    plt.savefig("hist.png")
    plt.close()

    plt.scatter(df["weight"], df["mpg"])
    plt.title("MPG vs Weight")
    plt.savefig("weight.png")
    plt.close()

    plt.scatter(df["horsepower"], df["mpg"])
    plt.title("MPG vs Horsepower")
    plt.savefig("hp.png")
    plt.close()

    return (
        df.head(8),
        mean_val,
        var_val,
        "trend.png",
        "hist.png",
        "weight.png",
        "hp.png"
    )

def manual_analysis(distance, fuel):
    eff = distance / fuel

    result = pd.DataFrame({
        "Distance (km)": [distance],
        "Fuel (liters)": [fuel],
        "Efficiency (km/l)": [eff]
    })

    plt.bar(["Efficiency"], [eff])
    plt.title("Manual Fuel Efficiency")
    plt.savefig("manual.png")
    plt.close()

    return result, eff, "manual.png"

with gr.Blocks() as app:
    gr.Markdown("Fuel Consumption Analysis Project")

    with gr.Tab("Dataset Analysis"):
        btn1 = gr.Button("Analyze Dataset")
        table = gr.Dataframe()
        mean_out = gr.Number(label="Mean MPG")
        var_out = gr.Number(label="Variance")
        img1 = gr.Image(label="Trend")
        img2 = gr.Image(label="Distribution")
        img3 = gr.Image(label="MPG vs Weight")
        img4 = gr.Image(label="MPG vs Horsepower")

        btn1.click(dataset_analysis,
                   outputs=[table, mean_out, var_out, img1, img2, img3, img4])

    with gr.Tab("Manual Input"):
        distance = gr.Number(label="Distance (km)")
        fuel  = gr.Number(label="Fuel (liters)")
        btn2 = gr.Button("Calculate")
        table2 = gr.Dataframe()
        eff_out = gr.Number(label="Efficiency")
        img5 = gr.Image()

        btn2.click(manual_analysis,
                   inputs=[distance , fuel],
                   outputs=[table2, eff_out, img5])

app.launch()